plugins:
  - "@html-eslint"
env:
  browser: true
  es2021: true
extends:
  - airbnb-base
overrides:
  - files: ["*.html"]
    parser: "@html-eslint/parser"
    extends: ["plugin:@html-eslint/recommended"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
